# This is a workflow used for runing automated tests
name: Verification

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events on the "main" branch
  pull_request:
    branches: [ "main" ]
    types: [edited, synchronize, opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job runs self-checking tests
  verif:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Run VUnit tests
        uses: VUnit/vunit_action@master
        with:
          cmd: hardware/run.py --gtkwave-fmt vcd

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: vunit_out
          retention-days: 10
